server:
  port: 8090

spring:
  application:
    name: virtual-power-plant
  datasource:
    url: jdbc:postgresql://postgres/power_plant_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      jdbc:
        batch_size: 25
      order_inserts: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
